-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 18:55:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SupremeCourtApp
-- -----------------------------------------------------
-- CS499 Supreme Court Database
-- - Handles articles, users, images, etc.

-- -----------------------------------------------------
-- Schema SupremeCourtApp
--
-- CS499 Supreme Court Database
-- - Handles articles, users, images, etc.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SupremeCourtApp` ;
USE `SupremeCourtApp` ;

-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(300) NOT NULL,
  `Source` VARCHAR(200) NOT NULL,
  `Author` VARCHAR(100) NULL,
  `Date` DATE NOT NULL,
  `Article Text` MEDIUMTEXT NOT NULL,
  `Article HTML` MEDIUMTEXT NOT NULL,
  `Title` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`User` (
  `Email` VARCHAR(500) NOT NULL,
  `Password` INT NOT NULL,
  `Permissions` INT NOT NULL,
  `Name` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `Image Location` VARCHAR(750) NOT NULL,
  `idArticle` INT NOT NULL,
  PRIMARY KEY (`idImage`),
  INDEX `idArticle_idx` (`idArticle` ASC),
  CONSTRAINT `idArticle`
    FOREIGN KEY (`idArticle`)
    REFERENCES `SupremeCourtApp`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`Article_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`Article_Keywords` (
  `idKey` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idKey`),
  UNIQUE INDEX `keyword_UNIQUE` (`keyword` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`Keyword_Instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`Keyword_Instances` (
  `idArticle` INT NOT NULL,
  `idInstance` INT NOT NULL AUTO_INCREMENT,
  `idKey` INT NOT NULL,
  PRIMARY KEY (`idInstance`),
  INDEX `idArticle_idx` (`idArticle` ASC),
  INDEX `idKey_idx` (`idKey` ASC),
  CONSTRAINT `idArticle2`
    FOREIGN KEY (`idArticle`)
    REFERENCES `SupremeCourtApp`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKey`
    FOREIGN KEY (`idKey`)
    REFERENCES `SupremeCourtApp`.`Article_Keywords` (`idKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
