-- MySQL Script generated by MySQL Workbench
-- Sat Oct 21 23:24:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SupremeCourtApp
-- -----------------------------------------------------
-- CS499 Supreme Court Database
-- - Handles articles, users, images, etc.

-- -----------------------------------------------------
-- Schema SupremeCourtApp
--
-- CS499 Supreme Court Database
-- - Handles articles, users, images, etc.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SupremeCourtApp` ;
USE `SupremeCourtApp` ;

-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `source` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `author` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `date` DATE NOT NULL,
  `article_text` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `title` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idArticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`user` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `password` INT NOT NULL,
  `permissions` INT NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `idArticle` INT NOT NULL,
  PRIMARY KEY (`idImage`),
  INDEX `idArticle_idx` (`idArticle` ASC),
  CONSTRAINT `idArticle`
    FOREIGN KEY (`idArticle`)
    REFERENCES `SupremeCourtApp`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`article_keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`article_keywords` (
  `idKey` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupremeCourtApp`.`keyword_instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupremeCourtApp`.`keyword_instances` (
  `idArticle` INT NOT NULL,
  `idInstance` INT NOT NULL AUTO_INCREMENT,
  `idKey` INT NOT NULL,
  PRIMARY KEY (`idInstance`),
  INDEX `idArticle_idx` (`idArticle` ASC),
  INDEX `idKey_idx` (`idKey` ASC),
  CONSTRAINT `idArticle2`
    FOREIGN KEY (`idArticle`)
    REFERENCES `SupremeCourtApp`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKey`
    FOREIGN KEY (`idKey`)
    REFERENCES `SupremeCourtApp`.`article_keywords` (`idKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
